import type { Metadata } from "next";
import Section from "@/components/Section";
import PillarGlyph from "@/components/PillarGlyph";

export const metadata: Metadata = {
  title: "Privacy Policy | Millecam",
  description: "How Millecam handles personal data.",
};

function H2({ children }: { children: string }) {
  return <h2 className="mt-10 font-serif text-xl font-semibold text-ink">{children}</h2>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-3 text-sm leading-relaxed text-ink/75">{children}</p>;
}
function LI({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-3">
      <PillarGlyph className="mt-1 h-3.5 w-2.5 shrink-0" />
      <span>{children}</span>
    </li>
  );
}

export default function PrivacyPolicyPage() {
  return (
    <Section className="pb-24 pt-16">
      <div className="mx-auto w-full max-w-3xl">
        <h1 className="font-serif text-4xl font-bold text-ink">Privacy Policy</h1>
        <p className="mt-4 text-sm text-muted">Last updated: 2 September 2026</p>

        <P>
          Millecam is a sole proprietorship of Robin Millecam, based at Sinte Annalaan 34, 9300 Aalst,
          Belgium (VAT BE 1026.876.048). For questions about this policy or how we handle your data, you
          can reach us at <a className="text-terracotta hover:underline" href="mailto:privacy@millecam.be">privacy@millecam.be</a>.
        </P>

        <H2>What data we collect</H2>
        <P>
          When you use the contact form on this website, we collect the data you provide yourself:
          name, company name, email address, phone number (optional), the subject of your enquiry, and
          your message. We don&apos;t collect any data via cookies or tracking technology. See the{" "}
          <a className="text-terracotta hover:underline" href="/en/cookiebeleid">Cookie Policy</a> for more
          details.
        </P>

        <H2>What we use this data for</H2>
        <P>
          Solely to respond to your question or request, and — if a collaboration follows — to start
          and manage that collaboration. We don&apos;t use your data for marketing purposes without your
          explicit consent, and we never sell or rent your data to third parties.
        </P>

        <H2>Legal basis</H2>
        <P>
          The processing of your contact details is based on our legitimate interest in responding to
          questions from (prospective) clients, and, once an engagement is discussed or entered into, on
          the performance of (pre-)contractual measures at your request (Art. 6(1)(b) and 6(1)(f) GDPR).
        </P>

        <H2>Who has access to your data</H2>
        <P>
          Your data is, in principle, only seen by Robin Millecam. For the technical operation of this
          website, we rely on two processors:
        </P>
        <ul className="mt-3 space-y-2 text-sm leading-relaxed text-ink/75">
          <LI>
            <span className="font-medium text-ink">Resend</span>: sends the email generated by the
            contact form. Resend may act as a processor outside the EU; we only work with parties that
            provide appropriate safeguards (such as standard contractual clauses).
          </LI>
          <LI>
            <span className="font-medium text-ink">Vercel</span>: hosts this website and, in doing so,
            processes technical data (such as IP addresses in server access logs) needed to keep the
            site running.
          </LI>
        </ul>

        <H2>Retention period</H2>
        <P>
          We retain data from the contact form for a maximum of 2 years after your last contact with
          Millecam, unless a longer retention period is legally required (for example under an ongoing
          agreement or accounting obligations).
        </P>

        <H2>Transfers outside the EU</H2>
        <P>
          Some of the processors named above may process data on servers outside the European Economic
          Area. In that case, we ensure this transfer takes place on the basis of an appropriate
          safeguard recognised by the GDPR (such as the European Commission&apos;s standard contractual
          clauses).
        </P>

        <H2>Security</H2>
        <P>
          We take reasonable technical and organisational measures to protect your data against loss,
          misuse or unauthorised access.
        </P>

        <H2>Your rights</H2>
        <P>Under the GDPR, you have the following rights regarding your personal data:</P>
        <ul className="mt-3 space-y-1.5 text-sm leading-relaxed text-ink/75">
          <LI>Access to the data we process about you</LI>
          <LI>Correction of inaccurate or incomplete data</LI>
          <LI>Erasure of your data (&apos;right to be forgotten&apos;)</LI>
          <LI>Restriction of processing</LI>
          <LI>Objection to processing</LI>
          <LI>Data portability</LI>
        </ul>
        <P>
          To exercise any of these rights, email{" "}
          <a className="text-terracotta hover:underline" href="mailto:privacy@millecam.be">privacy@millecam.be</a>. We respond
          within the legal term of one month.
        </P>

        <H2>Filing a complaint</H2>
        <P>
          Not satisfied with how we handle your data? Please contact us first. You also always have the
          right to file a complaint with the Belgian Data Protection Authority: Drukpersstraat 35, 1000
          Brussels,{" "}
          <a className="text-terracotta hover:underline" href="https://www.gegevensbeschermingsautoriteit.be" target="_blank" rel="noreferrer">
            gegevensbeschermingsautoriteit.be
          </a>.
        </P>

        <H2>Changes to this policy</H2>
        <P>
          We may update this privacy policy from time to time. The date at the top of this page
          indicates when the policy was last updated.
        </P>
      </div>
    </Section>
  );
}
